call-center-django/apps/call_center/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from .views import menu_action, index, call, join, heartbeat

app_name = 'call_center'
urlpatterns = [
    url(r'call/(?P<pk>\d+)/$', call, name="call"),
    url(r'call/(?P<pk>\d+)/join$', join, name="join"),
    url(r'call/(?P<pk>\d+)/heartbeat$', heartbeat, name="heartbeat"),
    url(r'call/(?P<pk>\d+)/menu/(?P<pressed_button>.+)$', menu_action, name="menu_action"),
    url(r'$', index, name="index"),
]

call-center-django/apps/dashboard/urls.py
from django.conf.urls import url, include
from .views import get_service_requests, accept_call, redirect_call, finish_call
app_name = 'dashboard'

urlpatterns = [
    url(r'accept/(?P<pk>\d+)$', accept_call, name="accept"),
    url(r'redirect/(?P<pk>\d+)$', redirect_call, name="redirect"),
    url(r'finish/(?P<pk>\d+)$', finish_call, name="finish"),
    url(r'$', get_service_requests, name="index"),
]

call-center-django/config/urls.py
from django.conf.urls import url, include
from django.conf.urls.static import static
from django.contrib import admin
from django.conf import settings
from .views import ExtraContentTemplateView

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^accounts/', include('allauth.urls')),
    url(r'^call_center/', include("call_center.urls")),
    url(r'^dashboard/', include("dashboard.urls")),
    url(r'^$', ExtraContentTemplateView.as_view(template_name='landing/index.html',
                                                extra_content={"landing": True}), name='index'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

call-center-django/apps/call_center/models.py
from django.db import models
from django.core.validators import RegexValidator
from django.contrib.auth.models import User


class ProblemCategory(models.Model):
    name = models.CharField(max_length=255)
    description = models.CharField(max_length=255)
    solution = models.FileField(upload_to='wavs', max_length=255,
                                default='wavs/greetings.wav')

    def __str__(self):
        return self.name

    class Meta:
        verbose_name_plural = "Problem categories"


class Menu(models.Model):
    parent = models.ForeignKey('self', blank=True, null=True)
    category = models.ForeignKey(ProblemCategory)
    button = models.DecimalField(max_digits=1, decimal_places=0)
    redirects_to_operator = models.BooleanField(default=False)

    class Meta:
        unique_together = (('parent', 'button'),)

    def __str__(self):
        return "{0} {1}".format(str(self.pk), self.category.name)


def root_menu():
    category, _ = ProblemCategory.objects.get_or_create(name="Root category",
                                                        description="Description")
    return Menu.objects.get_or_create(category=category, button=0)[0].pk


class Call(models.Model):
    LIVE_STATUS = 1
    DEAD_STATUS = 2
    STATUS_CHOICES = (
        (LIVE_STATUS, 'Live'),
        (DEAD_STATUS, 'Dead'),
    )

    last_heartbeat = models.DateTimeField(auto_now_add=True)
    start = models.DateTimeField(auto_now_add=True)
    end = models.DateTimeField(auto_now=True)
    phone_regex = RegexValidator(regex=r'^\+?1?\d{9,15}$',
                                 message="Phone number should be in format: '+999999999'."
                                 " Up to 15 digits allowed.")
    phone_number = models.CharField(validators=[phone_regex],
                                    max_length=255,
                                    blank=True)

    status = models.PositiveSmallIntegerField(default=LIVE_STATUS,
                                              choices=STATUS_CHOICES)
    menu_position = models.ForeignKey(Menu, default=root_menu)

    def __str__(self):
        return "{0} ({1}) {2}".format(self.phone_number,
                                      self.menu_position,
                                      self.status)

    def change_status(self, new_status):
        self.status = new_status
        self.save()
        if new_status == self.DEAD_STATUS:
            try:
                service_request = ServiceRequest.objects.get(call_id=self)
                service_request.change_status(ServiceRequest.COMPLETED)
            except ServiceRequest.DoesNotExist:
                pass

    def update_last_heartbeat(self, time):
        self.last_heartbeat = time
        self.save()

    def change_menu_position(self, pressed_button):
        new_position = Menu.objects.get(parent=self.menu_position, button=pressed_button)
        # Switch to new step of Menu
        self.menu_position = new_position
        self.save()
        if new_position.redirects_to_operator:
            sr = ServiceRequest.objects.create(category=new_position.category, call_id=self)
            sr.save()
        return new_position


class ServiceRequest(models.Model):
    CREATED = 2
    ACCEPTED = 1
    REDIRECTED = 3
    COMPLETED = 0
    REQUEST_STATUSES = [(CREATED, 'Created'),
                        (ACCEPTED, 'Accepted by operator'),
                        (REDIRECTED, 'Redirected to another operator'),
                        (COMPLETED, 'Completed')]

    created_at = models.DateTimeField(auto_now_add=True)
    completed_at = models.DateTimeField(auto_now=True)
    category = models.ForeignKey(ProblemCategory)

    operator_id = models.ForeignKey(User, blank=True, null=True)
    call_id = models.ForeignKey(Call)
    status = models.IntegerField(choices=REQUEST_STATUSES, default=CREATED)

    def __str__(self):
        return "Category: {} Status: {} Created_at: {}".format(self.category,
                                                               self.str_status,
                                                               self.created_at)

    @property
    def str_status(self):
        for status, str_status in self.REQUEST_STATUSES:
            if status == self.status:
                return str_status

    def change_status(self, new_status):
        self.status = new_status
        self.save()

    def accept_by(self, user):
        self.operator_id = user
        self.status = ServiceRequest.ACCEPTED
        self.save()

call-center-django/apps/call_center/views.py
from django.shortcuts import render, reverse, redirect
from django.http import HttpResponse
from django.views.decorators.csrf import csrf_exempt
import json
import os
from pprint import pprint
from config import celery_app
from django.utils import timezone
from .models import Call, Menu, ServiceRequest
# Create your views here.


@csrf_exempt
def menu_action(request, pk, pressed_button):
    call = Call.objects.get(pk=pk)
    try:
        menu = call.change_menu_position(pressed_button)
    except:
        menu = call.menu_position
    response = HttpResponse()
    response.write(menu.category.solution.read())
    response['Content-Length'] = menu.category.solution.size
    return response


@celery_app.task(bind=False)
def check_last_heartbeat(call_pk):
    call = Call.objects.get(pk=call_pk)
    delta_seconds = (timezone.now() - call.last_heartbeat) / timezone.timedelta(seconds=1)
    if delta_seconds > 20:
        print("{} stale".format(call_pk))
        call.change_status(Call.DEAD_STATUS)
        print("Updated status of {}".format(call_pk))
    else:
        print("{} not stale, adding new task".format(call_pk))
        check_last_heartbeat.apply_async((call_pk,), countdown=10)


def call(request, pk):
    call = Call.objects.get(pk=pk)
    context = {
        "call": call,
        "joined": False,
        "root_audio_url": call.menu_position.category.solution.url,
    }
    return render(request, "call_center/call.html", context=context)


def join(request, pk):
    context = {
        "call": Call.objects.get(pk=pk),
        "joined": True,
        "root_audio_url": None,
    }
    return render(request, "call_center/call.html", context=context)


def heartbeat(request, pk):
    Call.objects.get(pk=pk).update_last_heartbeat(timezone.now())
    return HttpResponse(status=200)


def index(request):
    if request.method == "POST":
        print(request.POST)
        phone_number = request.POST["phone_number"]
        phone_number = "+7" + phone_number
        call = Call(phone_number=phone_number)
        call.save()
        check_last_heartbeat.apply_async((call.pk,), countdown=10)
        return redirect("call_center:call", pk=call.pk)
    else:
        return render(request, "call_center/index.html")

call-center-django/apps/templates/call_center/call.html
{% extends "base-navbar.html" %}
{% load staticfiles %}

{% block content %}
<!--<div class="container">-->
<div class="left" style="padding-top:50px;">
    <div class="row" style="margin-top: 50px;">
        <div class="col-xs-12">
            <p class="lead"> Your number: {{ call.phone_number }}</p>
        </div>
        <audio id="audio">
            <source id="audio_source" src="{{ root_audio_url }}">
        </audio>
    </div>
    {% if not joined %}
    <div class="row" style="margin-top: 100px;">
        <div class="col-xs-12">
            <div class="btn-group">
                <button type="button" class="btn btn-default btn-keypad" value="1">1</button>
                <button type="button" class="btn btn-default btn-keypad" value="2">2</button>
                <button type="button" class="btn btn-default btn-keypad" value="3">3</button>
            </div>
            <br>
            <div class="btn-group">
                <button type="button" class="btn btn-default btn-keypad" value="4">4</button>
                <button type="button" class="btn btn-default btn-keypad" value="5">5</button>
                <button type="button" class="btn btn-default btn-keypad" value="6">6</button>
            </div>
            <br>
            <div class="btn-group">
                <button type="button" class="btn btn-default btn-keypad" value="7">7</button>
                <button type="button" class="btn btn-default btn-keypad" value="8">8</button>
                <button type="button" class="btn btn-default btn-keypad" value="9">9</button>
            </div>
            <br>
            <div class="btn-group">
                <button type="button" class="btn btn-default btn-keypad" value="*" disabled="1">*</button>
                <button type="button" class="btn btn-default btn-keypad" value="0">0</button>
                <button type="button" class="btn btn-default btn-keypad" value="#" disabled="1">#</button>
            </div>
        </div>
    </div>
    {% endif %}
</div>
<div class="right-white" id="videos" style="padding-top:50px;">
    <div class="row">
       <video id="localVideo" style="display:none;" autoplay muted></video>
       <video id="remoteVideo" autoplay></video>
   </div>
   {% if joined %}
   <div class="row" style="margin-top: 20px;">
   <form class="col-md-6" method="post" action="{% url 'dashboard:redirect' pk=call.pk %}">
       {% csrf_token %}
       <button class="btn btn-warning btn-block" type="submit">Redirect</button>
   </form>
   <form class="col-md-6" method="post" action="{% url 'dashboard:finish' pk=call.pk %}">
       {% csrf_token %}
       <button class="btn btn-danger btn-block" type="submit">Finish</button>
   </form>
   </div>
   {% else %}
   <form class="row" method="get" action="{% url 'call_center:index' %}">
       {% csrf_token %}
       <button class="btn btn-danger btn-block" type="submit">Finish</button>
   </form>
   {% endif %}

</div>
<!--</div>-->
{% endblock %}


{% block extra_body %}
    <script src="https://cdn.socket.io/socket.io-1.4.5.js"></script>
    <script src="{% static 'adapter.js' %}"></script>
    <script type="text/javascript">
        var room = {{ call.pk }};
    </script>
    <script src="{% static 'main.js' %}"></script>
    {% if not joined %}
        <script type="text/javascript">
            var audio = $("#audio")[0];
            var audio_source = $("#audio_source")[0];
            audio.play();
            $(".btn-keypad").click(function(event) {
                var val = $(event.target).attr("value");
                //var link = "/call-center/call/" + "{{ call.pk }}" + "/menu/" + val;
                var fmt_string = '{% url "call_center:menu_action" pk=call.pk pressed_button="pressed_button"%}';
                var link = fmt_string.replace("pressed_button", val);
                console.log(link);
                audio_source.src = link;
                audio.load();
                audio.play();
            });
        </script>
        <script type="text/javascript">
            setInterval(function() {
                $.ajax({
                     url: "{% url 'call_center:heartbeat' pk=call.pk %}",
                })
            }, 5000);
        </script>
    {% endif %}
{% endblock %}

call-center-django/apps/templates/call_center/index.html
{% extends "base-navbar.html" %}

{% block content %}
<div class="container" style="padding-top:50px; width: 100%;">
    <div class="row">
        <div class="col-xs-12">
            <form method="post" action="{% url 'call_center:index' %}" data-toggle="validator" role="form">
                {% csrf_token %}

                <div class="form-group">
                  <label for="phone_number" class="control-label">Phone number</label>
                  <div class="input-group">
                      <span class="input-group-addon" id="basic-addon1">+7</span>
                      <input type="text" class="form-control"
                             id="phone_number"
                             placeholder="Phone number"
                             pattern="^[0-9]{1,15}$"
                             name="phone_number"
                             aria-describedby="basic-addon1"
                             data-error="That phone number is invalid"
                             required></input>
                      <div class="input-group-btn">
                      <button type="submit" class="btn btn-success">Submit</button>
                      </div>
                  </div>
                  <div class="help-block with-errors"></div>
                </div>

                <!--<div class="form-group">
                  <label for="inputEmail" class="control-label">Email</label>
                  <input type="email" class="form-control" id="inputEmail" placeholder="Email" data-error="Bruh, that email address is invalid" required>
                  <div class="help-block with-errors"></div>
              </div>-->

            </form>
        </div>
    </div>
</div>
{% endblock %}