call-center-django/apps/dashboard/urls.py
from django.conf.urls import url, include
from .views import get_service_requests, accept_call, redirect_call, finish_call
app_name = 'dashboard'

urlpatterns = [
    url(r'accept/(?P<pk>\d+)$', accept_call, name="accept"),
    url(r'redirect/(?P<pk>\d+)$', redirect_call, name="redirect"),
    url(r'finish/(?P<pk>\d+)$', finish_call, name="finish"),
    url(r'$', get_service_requests, name="index"),
]

call-center-django/config/urls.py
from django.conf.urls import url, include
from django.conf.urls.static import static
from django.contrib import admin
from django.conf import settings
from .views import ExtraContentTemplateView

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^accounts/', include('allauth.urls')),
    url(r'^call_center/', include("call_center.urls")),
    url(r'^dashboard/', include("dashboard.urls")),
    url(r'^$', ExtraContentTemplateView.as_view(template_name='landing/index.html',
                                                extra_content={"landing": True}), name='index'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

call-center-django/apps/dashboard/models.py
from django.db import models
from call_center.models import ProblemCategory, ServiceRequest
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.dispatch import receiver
# Create your models here.


class Operator(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    categories = models.ManyToManyField(ProblemCategory)

    def get_service_requests(self):
        requests = (ServiceRequest.objects.filter(category__in=self.categories.all(),
                                                  status__in=[ServiceRequest.CREATED,
                                                              ServiceRequest.REDIRECTED])
                                          .exclude(operator_id=self.user).order_by('status')[:10])
        return requests

    def __str__(self):
        return "Name: {} categories: {}".format(self.user.username,
                                                (" "
                                                 .join(map(lambda x: x.name,
                                                           self.categories.all()))))


@receiver(post_save, sender=User)
def create_operator(sender, instance, **kwargs):
    operator, created = Operator.objects.get_or_create(user=instance)

call-center-django/apps/dashboard/views.py
from django.shortcuts import render, reverse, redirect
from .models import Operator
from call_center.models import Call, ServiceRequest
from django.contrib.auth.decorators import login_required
from django.views.decorators.http import require_POST
# Create your views here.


@login_required
def get_service_requests(request):
    context = {'requests': Operator.objects.get(user=request.user).get_service_requests()}
    return render(request, "dashboard/dashboard.html", context=context)


@login_required
@require_POST
def accept_call(request, pk):
    ServiceRequest.objects.get(call_id__pk=pk).accept_by(request.user)
    return redirect('call_center:join', pk=pk)


@login_required
@require_POST
def redirect_call(request, pk):
    ServiceRequest.objects.get(call_id__pk=pk).change_status(ServiceRequest.REDIRECTED)
    return redirect('dashboard:index')


@login_required
@require_POST
def finish_call(request, pk):
    ServiceRequest.objects.get(call_id__pk=pk).change_status(ServiceRequest.COMPLETED)
    return redirect('dashboard:index')

call-center-django/apps/templates/dashboard/dashboard.html
{% extends "base-navbar.html" %}

{% block content %}
    <div class="container" style="padding-top: 50px;">
        <h2 class="heading">Service Requests</h2>
        <table class="table table-striped">
            <thead>
                <th>Phone Number</th>
                <th>Category</th>
                <th>Status</th>
                <th>Created</th>
                <th>Accept</th>
            </thead>
            {% for request in requests %}
                <tr>
                    <td>{{request.call_id.phone_number}}</td>
                    <td>{{request.category}}</td>
                    <td>{{request.str_status}}</td>
                    <td>{{request.created_at}}</td>
                    <td>
                        <form method="post" action="{% url 'dashboard:accept' pk=request.call_id.pk %}">
                            {% csrf_token %}
                            <button class="btn btn-success" type="submit">Accept</button>
                        </form>
                    </td>
                </tr>
            {% endfor %}
        </table>
    </div>
{% endblock %}