call-center-django/apps/call_center/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from .views import menu_action, index, call, join, heartbeat

app_name = 'call_center'
urlpatterns = [
    url(r'call/(?P<pk>\d+)/$', call, name="call"),
    url(r'call/(?P<pk>\d+)/join$', join, name="join"),
    url(r'call/(?P<pk>\d+)/heartbeat$', heartbeat, name="heartbeat"),
    url(r'call/(?P<pk>\d+)/menu/(?P<pressed_button>.+)$', menu_action, name="menu_action"),
    url(r'$', index, name="index"),
]

call-center-django/apps/dashboard/urls.py
from django.conf.urls import url, include
from .views import get_service_requests, accept_call, redirect_call, finish_call
app_name = 'dashboard'

urlpatterns = [
    url(r'accept/(?P<pk>\d+)$', accept_call, name="accept"),
    url(r'redirect/(?P<pk>\d+)$', redirect_call, name="redirect"),
    url(r'finish/(?P<pk>\d+)$', finish_call, name="finish"),
    url(r'$', get_service_requests, name="index"),
]

call-center-django/config/urls.py
from django.conf.urls import url, include
from django.conf.urls.static import static
from django.contrib import admin
from django.conf import settings
from .views import ExtraContentTemplateView

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^accounts/', include('allauth.urls')),
    url(r'^call_center/', include("call_center.urls")),
    url(r'^dashboard/', include("dashboard.urls")),
    url(r'^$', ExtraContentTemplateView.as_view(template_name='landing/index.html',
                                                extra_content={"landing": True}), name='index'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

call-center-django/apps/templates/landing/index.html
{% extends "base.html" %}
{% load staticfiles %}
{% block content%}
<div class="left">
    <form action="{%url 'call_center:index'%}">
    <button class="btn btn-lg btn-choice btn-success">Client</button>
    </form>
</div>
<div class="right">
    <form action="{%url 'dashboard:index'%}">
    <button class="btn btn-lg btn-danger btn-choice btn-danger">Operator</button>
    </from>
</div>


{% endblock %}

{% block extra_body %}

{% endblock %}